export const ADD_ITEM = 'ADD_ITEM'
export const DELETE_ITEM = 'DELETE_ITEM'
export const COMPLETE_ITEM = 'COMPLETE_ITEM,'
export const HANDLE_INPUT = 'HANDLE_INPUT'
export const CHANGE_STATUS = 'CHANGE_STATUS'
